--- 
:document: 
  :source: document.glyph
  :author: Fabio Cevasco
  :title: Ruby Compendium
  :subtitle: An Essential Guide to the Ruby Ecosystem
  :filename: ruby-compendium
  :revision: Rev. 0.2.0
  :draft: false
  :output: pdf
  :styles: embed
:output: 
  :h3rald:
    :multifile: true
    :extension: .html
    :filter_target: html
    :base: /ruby-compendium/book/
    :macro_reps: html5
    :layout_dir: web5
    :layouts:
      :topic: bookpage
      :index: bookindex
  :pdf: 
    :generator: prince
